#!/bin/sh
#
# prerm script for the Debian GNU/Linux python-roy-doc package
#
# Dirk Eddelbuettel <edd@debian.org>   

set -e

#DEBHELPER#

case "$1" in
    remove|purge)
	install-info --quiet --remove rpy
    ;;

    upgrade)
    ;;

    failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac                 
