#!/usr/bin/env python2.6

# Take in a sets_overlap.pl output file and convert it to 
# the java heatmap sets input file
# 

import sys

connections = {}

gold_sets = []
test_sets = []

gold_sets_hash = {}
for line in sys.stdin:

	if line.startswith(">"):
		test_sets.append(line.rstrip()[1:])
		connections[line.rstrip()[1:]] = {}
		continue
		
	parts = line.rstrip().split(",")
	gold_set, score = parts[0], parts[1]

	connections[test_sets[-1]][gold_set] = score	

	gold_sets_hash[gold_set] = 1

for set in gold_sets_hash:
	gold_sets.append(set)

# print columns
header = ""
for set in test_sets:
	header += "\t"+set
print "ROWS"+header

# print metadata: edit as needed
print "METADATA\tWIDTH^800\tHEIGHT^800\tOUTPUT^gif\tFILENAME^heatmap.gif"

# print rows
for test_set in test_sets:

	printline = test_set

	for gold_set in sorted(gold_sets):
		score = None
		if gold_set in connections[test_set]:
			score = connections[test_set][gold_set]
		else:
			score = "0"
		printline += "\t"+gold_set+"^"+score	

	print printline	

